// ./frontend/nginx.conf
server {
  listen 80;
  server_name localhost;

  # Директория с собранными статическими файлами
  root /usr/share/nginx/html;
  index index.html;

  location / {
    # Эта директива - ключ к работе SPA.
    # Nginx сначала пытается найти файл по точному URI ($uri),
    # затем - директорию ($uri/),
    # и если ничего не найдено, он отдает /index.html.
    # React Router уже на клиенте разбирает URL и показывает нужный компонент.
    try_files $uri $uri/ /index.html;
  }
}